-- AgroGemini Oracle v4 - separação por grupos lógicos
-- Arquivo: 01_tabelas_base.sql
-- Objetivo: tabelas base/suporte (enderecos, usuarios, telefones_usuarios).

-- 3b. CREATE TABLE com constraints nomeadas
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE enderecos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_ENDERECOS PRIMARY KEY,
    cep VARCHAR2(8) CONSTRAINT NN_ENDERECOS_CEP NOT NULL,
    logradouro VARCHAR2(150) CONSTRAINT NN_ENDERECOS_LOGRADOURO NOT NULL,
    numero VARCHAR2(20) CONSTRAINT NN_ENDERECOS_NUMERO NOT NULL,
    complemento VARCHAR2(100),
    bairro VARCHAR2(100) CONSTRAINT NN_ENDERECOS_BAIRRO NOT NULL,
    cidade VARCHAR2(100) CONSTRAINT NN_ENDERECOS_CIDADE NOT NULL,
    estado VARCHAR2(2) CONSTRAINT NN_ENDERECOS_ESTADO NOT NULL,
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    pais VARCHAR2(60) DEFAULT 'Brasil' CONSTRAINT NN_ENDERECOS_PAIS NOT NULL,
    CONSTRAINT CK_ENDERECOS_CEP CHECK (REGEXP_LIKE(cep, '^[0-9]{8}$')),
    CONSTRAINT CK_ENDERECOS_ESTADO CHECK (REGEXP_LIKE(estado, '^[A-Z]{2}$'))
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_USUARIOS PRIMARY KEY,
    nome VARCHAR2(100) CONSTRAINT NN_USUARIOS_NOME NOT NULL,
    sobrenome VARCHAR2(150) CONSTRAINT NN_USUARIOS_SOBRENOME NOT NULL,
    email VARCHAR2(254) CONSTRAINT NN_USUARIOS_EMAIL NOT NULL,
    senha_hash VARCHAR2(100) CONSTRAINT NN_USUARIOS_SENHA_HASH NOT NULL,
    tipo_usuario VARCHAR2(3) CONSTRAINT NN_USUARIOS_TIPO NOT NULL,
    endereco_id NUMBER,
    ativo CHAR(1) DEFAULT 'Y' CONSTRAINT NN_USUARIOS_ATIVO NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_USUARIOS_CRIADO_EM NOT NULL,
    ultimo_acesso TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UQ_USUARIOS_EMAIL UNIQUE (email),
    CONSTRAINT CK_USUARIOS_TIPO CHECK (tipo_usuario IN ('UE','UP','UC','ADM')),
    CONSTRAINT CK_USUARIOS_ATIVO CHECK (ativo IN ('Y','N')),
    CONSTRAINT FK_USUARIOS_ENDERECOS FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE telefones_usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_TEL_USUARIOS PRIMARY KEY,
    usuario_id NUMBER CONSTRAINT NN_TEL_USUARIOS_USUARIO_ID NOT NULL,
    numero VARCHAR2(20) CONSTRAINT NN_TEL_USUARIOS_NUMERO NOT NULL,
    tipo VARCHAR2(15) CONSTRAINT NN_TEL_USUARIOS_TIPO NOT NULL,
    whatsapp CHAR(1) DEFAULT 'N' CONSTRAINT NN_TEL_USUARIOS_WHATSAPP NOT NULL,
    CONSTRAINT CK_TEL_USUARIOS_TIPO CHECK (tipo IN ('MOVEL','FIXO','COMERCIAL')),
    CONSTRAINT CK_TEL_USUARIOS_WHATSAPP CHECK (whatsapp IN ('Y','N')),
    CONSTRAINT FK_TEL_USUARIOS_USUARIOS FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /

-- 3c. COMMENT ON TABLE / COMMENT ON COLUMN
COMMENT ON TABLE enderecos IS 'Catálogo de endereços reutilizado por usuários, fazendas e laboratórios.';
COMMENT ON COLUMN enderecos.id IS 'Identificador técnico do endereço.';
COMMENT ON COLUMN enderecos.cep IS 'CEP sem máscara, com 8 dígitos.';
COMMENT ON COLUMN enderecos.logradouro IS 'Logradouro.';
COMMENT ON COLUMN enderecos.numero IS 'Número ou identificação equivalente.';
COMMENT ON COLUMN enderecos.complemento IS 'Complemento opcional.';
COMMENT ON COLUMN enderecos.bairro IS 'Bairro ou distrito.';
COMMENT ON COLUMN enderecos.cidade IS 'Cidade.';
COMMENT ON COLUMN enderecos.estado IS 'UF com duas letras.';
COMMENT ON COLUMN enderecos.latitude IS 'Latitude do endereço, quando conhecida.';
COMMENT ON COLUMN enderecos.longitude IS 'Longitude do endereço, quando conhecida.';
COMMENT ON COLUMN enderecos.pais IS 'País do endereço.';
COMMENT ON TABLE usuarios IS 'Cadastro de pessoas físicas e operadores do sistema.';
COMMENT ON COLUMN usuarios.id IS 'Identificador do usuário.';
COMMENT ON COLUMN usuarios.nome IS 'Nome.';
COMMENT ON COLUMN usuarios.sobrenome IS 'Sobrenome.';
COMMENT ON COLUMN usuarios.email IS 'Email único de login.';
COMMENT ON COLUMN usuarios.senha_hash IS 'Hash da senha.';
COMMENT ON COLUMN usuarios.tipo_usuario IS 'UE, UP, UC ou ADM.';
COMMENT ON COLUMN usuarios.endereco_id IS 'Endereço principal.';
COMMENT ON COLUMN usuarios.ativo IS 'Indicador Y/N.';
COMMENT ON COLUMN usuarios.criado_em IS 'Data de criação.';
COMMENT ON COLUMN usuarios.ultimo_acesso IS 'Último acesso autenticado.';
COMMENT ON TABLE telefones_usuarios IS 'Telefones de contato associados aos usuários.';
COMMENT ON COLUMN telefones_usuarios.id IS 'Identificador do telefone.';
COMMENT ON COLUMN telefones_usuarios.usuario_id IS 'Usuário dono do telefone.';
COMMENT ON COLUMN telefones_usuarios.numero IS 'Número telefônico.';
COMMENT ON COLUMN telefones_usuarios.tipo IS 'Móvel, fixo ou comercial.';
COMMENT ON COLUMN telefones_usuarios.whatsapp IS 'Indicador Y/N.';
