-- AgroGemini Oracle v4 - separação por grupos lógicos
-- Arquivo: 02_tabelas_negocio.sql
-- Objetivo: tabelas de negócio agronômico/laboratorial de cadastro.

    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE fazendas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_FAZENDAS PRIMARY KEY,
    nome VARCHAR2(150) CONSTRAINT NN_FAZENDAS_NOME NOT NULL,
    cpf_cnpj VARCHAR2(14) CONSTRAINT NN_FAZENDAS_CPF_CNPJ NOT NULL,
    endereco_id NUMBER,
    car VARCHAR2(30),
    area_total_ha NUMBER(12,2),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_FAZENDAS_CRIADO_EM NOT NULL,
    CONSTRAINT CK_FAZENDAS_CPF_CNPJ CHECK (REGEXP_LIKE(cpf_cnpj, '^[0-9]{11,14}$')),
    CONSTRAINT FK_FAZENDAS_ENDERECOS FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE fazenda_usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_FAZENDA_USUARIOS PRIMARY KEY,
    fazenda_id NUMBER CONSTRAINT NN_FAZENDA_USUARIOS_FAZENDA_ID NOT NULL,
    usuario_id NUMBER CONSTRAINT NN_FAZENDA_USUARIOS_USUARIO_ID NOT NULL,
    papel VARCHAR2(20) CONSTRAINT NN_FAZENDA_USUARIOS_PAPEL NOT NULL,
    inicio_vigencia DATE CONSTRAINT NN_FAZENDA_USUARIOS_INI_VIG NOT NULL,
    fim_vigencia DATE,
    CONSTRAINT UQ_FAZENDA_USUARIOS UNIQUE (fazenda_id, usuario_id, papel, inicio_vigencia),
    CONSTRAINT CK_FAZENDA_USUARIOS_PAPEL CHECK (papel IN ('DONO','FUNCIONARIO','GERENTE')),
    CONSTRAINT CK_FAZENDA_USUARIOS_VIGENCIA CHECK (fim_vigencia IS NULL OR fim_vigencia >= inicio_vigencia),
    CONSTRAINT FK_FAZENDA_USUARIOS_FAZENDAS FOREIGN KEY (fazenda_id) REFERENCES fazendas(id),
    CONSTRAINT FK_FAZENDA_USUARIOS_USUARIOS FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE talhoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_TALHOES PRIMARY KEY,
    fazenda_id NUMBER CONSTRAINT NN_TALHOES_FAZENDA_ID NOT NULL,
    identificacao VARCHAR2(100) CONSTRAINT NN_TALHOES_IDENTIFICACAO NOT NULL,
    tipo_plantio VARCHAR2(30) CONSTRAINT NN_TALHOES_TIPO_PLANTIO NOT NULL,
    area NUMBER(12,2),
    profundidade_amostragem_cm NUMBER(5,2),
    textura_solo VARCHAR2(20),
    bioma VARCHAR2(20),
    latitude_centroide NUMBER(10,7),
    longitude_centroide NUMBER(10,7),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_TALHOES_CRIADO_EM NOT NULL,
    CONSTRAINT UQ_TALHOES_FAZENDA_IDENT UNIQUE (fazenda_id, identificacao),
    CONSTRAINT CK_TALHOES_TIPO_PLANTIO CHECK (tipo_plantio IN ('CONVENCIONAL','DIRETO','IRRIGADO','SEQUEIRO','OUTRO')),
    CONSTRAINT CK_TALHOES_TEXTURA_SOLO CHECK (textura_solo IS NULL OR textura_solo IN ('ARENOSA','MEDIA','ARGILOSA','MUITO_ARGILOSA')),
    CONSTRAINT CK_TALHOES_BIOMA CHECK (bioma IS NULL OR bioma IN ('AMAZONIA','CERRADO','CAATINGA','MATA_ATLANTICA','PAMPA','PANTANAL')),
    CONSTRAINT FK_TALHOES_FAZENDAS FOREIGN KEY (fazenda_id) REFERENCES fazendas(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE laboratorios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_LABORATORIOS PRIMARY KEY,
    nome VARCHAR2(150) CONSTRAINT NN_LABORATORIOS_NOME NOT NULL,
    cnpj VARCHAR2(14) CONSTRAINT NN_LABORATORIOS_CNPJ NOT NULL,
    endereco_id NUMBER,
    email VARCHAR2(254) CONSTRAINT NN_LABORATORIOS_EMAIL NOT NULL,
    ativo CHAR(1) DEFAULT 'Y' CONSTRAINT NN_LABORATORIOS_ATIVO NOT NULL,
    acreditacao_iso17025 CHAR(1) DEFAULT 'N' CONSTRAINT NN_LABORATORIOS_ISO NOT NULL,
    registro_renasem VARCHAR2(30),
    credenciamento_mapa VARCHAR2(30),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_LABORATORIOS_CRIADO_EM NOT NULL,
    CONSTRAINT UQ_LABORATORIOS_CNPJ UNIQUE (cnpj),
    CONSTRAINT UQ_LABORATORIOS_EMAIL UNIQUE (email),
    CONSTRAINT CK_LABORATORIOS_CNPJ CHECK (REGEXP_LIKE(cnpj, '^[0-9]{14}$')),
    CONSTRAINT CK_LABORATORIOS_ATIVO CHECK (ativo IN ('Y','N')),
    CONSTRAINT CK_LABORATORIOS_ISO CHECK (acreditacao_iso17025 IN ('Y','N')),
    CONSTRAINT FK_LABORATORIOS_ENDERECOS FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE laboratorio_usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_LAB_USUARIOS PRIMARY KEY,
    laboratorio_id NUMBER CONSTRAINT NN_LAB_USUARIOS_LAB_ID NOT NULL,
    usuario_id NUMBER CONSTRAINT NN_LAB_USUARIOS_USUARIO_ID NOT NULL,
    papel VARCHAR2(25) CONSTRAINT NN_LAB_USUARIOS_PAPEL NOT NULL,
    registro_crea VARCHAR2(30),
    CONSTRAINT UQ_LAB_USUARIOS UNIQUE (laboratorio_id, usuario_id, papel),
    CONSTRAINT CK_LAB_USUARIOS_PAPEL CHECK (papel IN ('TECNICO','GESTOR','RESPONSAVEL_TECNICO','ADMINISTRADOR')),
    CONSTRAINT FK_LAB_USUARIOS_LABORATORIOS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_LAB_USUARIOS_USUARIOS FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE telefones_laboratorios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_TEL_LABS PRIMARY KEY,
    laboratorio_id NUMBER CONSTRAINT NN_TEL_LABS_LAB_ID NOT NULL,
    numero VARCHAR2(20) CONSTRAINT NN_TEL_LABS_NUMERO NOT NULL,
    tipo VARCHAR2(15) CONSTRAINT NN_TEL_LABS_TIPO NOT NULL,
    CONSTRAINT CK_TEL_LABS_TIPO CHECK (tipo IN ('MOVEL','FIXO','COMERCIAL')),
    CONSTRAINT FK_TEL_LABS_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /

COMMENT ON TABLE fazendas IS 'Unidades produtivas rurais cadastradas na plataforma.';
COMMENT ON COLUMN fazendas.id IS 'Identificador da fazenda.';
COMMENT ON COLUMN fazendas.nome IS 'Nome da fazenda.';
COMMENT ON COLUMN fazendas.cpf_cnpj IS 'Documento sem máscara.';
COMMENT ON COLUMN fazendas.endereco_id IS 'Endereço principal.';
COMMENT ON COLUMN fazendas.car IS 'Cadastro Ambiental Rural.';
COMMENT ON COLUMN fazendas.area_total_ha IS 'Área total em hectares.';
COMMENT ON COLUMN fazendas.criado_em IS 'Data de criação.';
COMMENT ON TABLE fazenda_usuarios IS 'Vínculo entre fazendas e usuários com papel e vigência.';
COMMENT ON COLUMN fazenda_usuarios.id IS 'Identificador da associação.';
COMMENT ON COLUMN fazenda_usuarios.fazenda_id IS 'Fazenda vinculada.';
COMMENT ON COLUMN fazenda_usuarios.usuario_id IS 'Usuário vinculado.';
COMMENT ON COLUMN fazenda_usuarios.papel IS 'DONO, FUNCIONARIO ou GERENTE.';
COMMENT ON COLUMN fazenda_usuarios.inicio_vigencia IS 'Início da vigência do vínculo.';
COMMENT ON COLUMN fazenda_usuarios.fim_vigencia IS 'Fim da vigência do vínculo.';
COMMENT ON TABLE talhoes IS 'Subdivisões operacionais de fazendas, base para rastreabilidade e geoespacial.';
COMMENT ON COLUMN talhoes.id IS 'Identificador do talhão.';
COMMENT ON COLUMN talhoes.fazenda_id IS 'Fazenda do talhão.';
COMMENT ON COLUMN talhoes.identificacao IS 'Código/nome do talhão.';
COMMENT ON COLUMN talhoes.tipo_plantio IS 'Tipo de plantio.';
COMMENT ON COLUMN talhoes.area IS 'Área em hectares.';
COMMENT ON COLUMN talhoes.profundidade_amostragem_cm IS 'Profundidade padrão.';
COMMENT ON COLUMN talhoes.textura_solo IS 'Textura do solo.';
COMMENT ON COLUMN talhoes.bioma IS 'Bioma predominante.';
COMMENT ON COLUMN talhoes.latitude_centroide IS 'Latitude do centróide.';
COMMENT ON COLUMN talhoes.longitude_centroide IS 'Longitude do centróide.';
COMMENT ON COLUMN talhoes.criado_em IS 'Data de criação.';
COMMENT ON TABLE laboratorios IS 'Laboratórios/consultorias que operam o sistema.';
COMMENT ON COLUMN laboratorios.id IS 'Identificador do laboratório.';
COMMENT ON COLUMN laboratorios.nome IS 'Nome do laboratório.';
COMMENT ON COLUMN laboratorios.cnpj IS 'CNPJ sem máscara.';
COMMENT ON COLUMN laboratorios.endereco_id IS 'Endereço principal.';
COMMENT ON COLUMN laboratorios.email IS 'Email principal.';
COMMENT ON COLUMN laboratorios.ativo IS 'Indicador Y/N.';
COMMENT ON COLUMN laboratorios.acreditacao_iso17025 IS 'Indicador Y/N.';
COMMENT ON COLUMN laboratorios.registro_renasem IS 'Registro RENASEM.';
COMMENT ON COLUMN laboratorios.credenciamento_mapa IS 'Credenciamento MAPA.';
COMMENT ON COLUMN laboratorios.criado_em IS 'Data de criação.';
COMMENT ON TABLE laboratorio_usuarios IS 'Vínculo entre laboratório e seus usuários internos.';
COMMENT ON COLUMN laboratorio_usuarios.id IS 'Identificador da associação.';
COMMENT ON COLUMN laboratorio_usuarios.laboratorio_id IS 'Laboratório.';
COMMENT ON COLUMN laboratorio_usuarios.usuario_id IS 'Usuário.';
COMMENT ON COLUMN laboratorio_usuarios.papel IS 'TECNICO, GESTOR, RESPONSAVEL_TECNICO ou ADMINISTRADOR.';
COMMENT ON COLUMN laboratorio_usuarios.registro_crea IS 'Registro CREA/CRQ.';
COMMENT ON TABLE telefones_laboratorios IS 'Telefones de contato do laboratório.';
COMMENT ON COLUMN telefones_laboratorios.id IS 'Identificador do telefone.';
COMMENT ON COLUMN telefones_laboratorios.laboratorio_id IS 'Laboratório.';
COMMENT ON COLUMN telefones_laboratorios.numero IS 'Número telefônico.';
COMMENT ON COLUMN telefones_laboratorios.tipo IS 'Móvel, fixo ou comercial.';
