-- AgroGemini Oracle v4 - separação por grupos lógicos
-- Arquivo: 03_tabelas_comercial.sql
-- Objetivo: tabelas comerciais (planos e assinaturas).

    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE planos_assinaturas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_PLANOS PRIMARY KEY,
    tipo VARCHAR2(20) CONSTRAINT NN_PLANOS_TIPO NOT NULL,
    valor NUMBER(12,2) CONSTRAINT NN_PLANOS_VALOR NOT NULL,
    descricao CLOB,
    limite_amostras NUMBER CONSTRAINT NN_PLANOS_LIMITE_AMOSTRAS NOT NULL,
    limite_usuarios NUMBER CONSTRAINT NN_PLANOS_LIMITE_USUARIOS NOT NULL,
    permite_api CHAR(1) DEFAULT 'N' CONSTRAINT NN_PLANOS_PERMITE_API NOT NULL,
    ativo CHAR(1) DEFAULT 'Y' CONSTRAINT NN_PLANOS_ATIVO NOT NULL,
    CONSTRAINT UQ_PLANOS_TIPO UNIQUE (tipo),
    CONSTRAINT CK_PLANOS_TIPO CHECK (tipo IN ('BASICO','PREMIUM')),
    CONSTRAINT CK_PLANOS_PERMITE_API CHECK (permite_api IN ('Y','N')),
    CONSTRAINT CK_PLANOS_ATIVO CHECK (ativo IN ('Y','N'))
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE assinaturas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_ASSINATURAS PRIMARY KEY,
    laboratorio_id NUMBER CONSTRAINT NN_ASSINATURAS_LAB_ID NOT NULL,
    plano_id NUMBER CONSTRAINT NN_ASSINATURAS_PLANO_ID NOT NULL,
    numero_contrato VARCHAR2(50) CONSTRAINT NN_ASSINATURAS_NUM_CONTRATO NOT NULL,
    arquivo_contrato CLOB,
    data_inicio DATE CONSTRAINT NN_ASSINATURAS_DATA_INICIO NOT NULL,
    data_expiracao DATE CONSTRAINT NN_ASSINATURAS_DATA_EXP NOT NULL,
    status VARCHAR2(15) CONSTRAINT NN_ASSINATURAS_STATUS NOT NULL,
    renovacao_automatica CHAR(1) DEFAULT 'N' CONSTRAINT NN_ASSINATURAS_RENOV_AUTO NOT NULL,
    amostras_consumidas NUMBER DEFAULT 0 CONSTRAINT NN_ASSINATURAS_AMOSTRAS_CONSUMIDAS NOT NULL,
    CONSTRAINT UQ_ASSINATURAS_NUM_CONTRATO UNIQUE (numero_contrato),
    CONSTRAINT CK_ASSINATURAS_STATUS CHECK (status IN ('ATIVA','SUSPENSA','CANCELADA','EXPIRADA')),
    CONSTRAINT CK_ASSINATURAS_RENOV_AUTO CHECK (renovacao_automatica IN ('Y','N')),
    CONSTRAINT CK_ASSINATURAS_DATAS CHECK (data_expiracao >= data_inicio),
    CONSTRAINT FK_ASSINATURAS_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_ASSINATURAS_PLANOS FOREIGN KEY (plano_id) REFERENCES planos_assinaturas(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /

COMMENT ON TABLE planos_assinaturas IS 'Planos comerciais SaaS ofertados ao laboratório.';
COMMENT ON COLUMN planos_assinaturas.id IS 'Identificador do plano.';
COMMENT ON COLUMN planos_assinaturas.tipo IS 'BASICO ou PREMIUM.';
COMMENT ON COLUMN planos_assinaturas.valor IS 'Valor do plano.';
COMMENT ON COLUMN planos_assinaturas.descricao IS 'Descrição comercial.';
COMMENT ON COLUMN planos_assinaturas.limite_amostras IS 'Limite de amostras.';
COMMENT ON COLUMN planos_assinaturas.limite_usuarios IS 'Limite de usuários.';
COMMENT ON COLUMN planos_assinaturas.permite_api IS 'Indicador Y/N.';
COMMENT ON COLUMN planos_assinaturas.ativo IS 'Indicador Y/N.';
COMMENT ON TABLE assinaturas IS 'Assinaturas ativas, suspensas ou expiradas dos laboratórios.';
COMMENT ON COLUMN assinaturas.id IS 'Identificador da assinatura.';
COMMENT ON COLUMN assinaturas.laboratorio_id IS 'Laboratório assinante.';
COMMENT ON COLUMN assinaturas.plano_id IS 'Plano contratado.';
COMMENT ON COLUMN assinaturas.numero_contrato IS 'Número do contrato.';
COMMENT ON COLUMN assinaturas.arquivo_contrato IS 'Caminho ou conteúdo externo do contrato.';
COMMENT ON COLUMN assinaturas.data_inicio IS 'Início da vigência.';
COMMENT ON COLUMN assinaturas.data_expiracao IS 'Fim da vigência.';
COMMENT ON COLUMN assinaturas.status IS 'ATIVA, SUSPENSA, CANCELADA, EXPIRADA.';
COMMENT ON COLUMN assinaturas.renovacao_automatica IS 'Indicador Y/N.';
COMMENT ON COLUMN assinaturas.amostras_consumidas IS 'Consumo acumulado.';
