-- AgroGemini Oracle v4 - separação por grupos lógicos
-- Arquivo: 04_tabelas_laboratorial.sql
-- Objetivo: tabelas do fluxo laboratorial e cálculo.

    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE importacoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_IMPORTACOES PRIMARY KEY,
    laboratorio_id NUMBER CONSTRAINT NN_IMPORTACOES_LAB_ID NOT NULL,
    usuario_id NUMBER CONSTRAINT NN_IMPORTACOES_USUARIO_ID NOT NULL,
    nome_arquivo VARCHAR2(255) CONSTRAINT NN_IMPORTACOES_NOME_ARQUIVO NOT NULL,
    tipo_arquivo VARCHAR2(10) CONSTRAINT NN_IMPORTACOES_TIPO_ARQUIVO NOT NULL,
    formato_instrumento VARCHAR2(40),
    caminho_arquivo CLOB CONSTRAINT NN_IMPORTACOES_CAMINHO_ARQ NOT NULL,
    hash_arquivo VARCHAR2(128) CONSTRAINT NN_IMPORTACOES_HASH_ARQUIVO NOT NULL,
    status VARCHAR2(15) CONSTRAINT NN_IMPORTACOES_STATUS NOT NULL,
    mensagem_erro CLOB,
    total_registros NUMBER DEFAULT 0 CONSTRAINT NN_IMPORTACOES_TOTAL_REGISTROS NOT NULL,
    registros_processados NUMBER DEFAULT 0 CONSTRAINT NN_IMPORTACOES_REG_PROC NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_IMPORTACOES_CRIADO_EM NOT NULL,
    processado_em TIMESTAMP WITH TIME ZONE,
    CONSTRAINT CK_IMPORTACOES_TIPO_ARQUIVO CHECK (tipo_arquivo IN ('CSV','XLSX')),
    CONSTRAINT CK_IMPORTACOES_STATUS CHECK (status IN ('ENVIADO','PROCESSANDO','PROCESSADO','ERRO')),
    CONSTRAINT FK_IMPORTACOES_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_IMPORTACOES_USUARIOS FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE amostras (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_AMOSTRAS PRIMARY KEY,
    talhao_id NUMBER CONSTRAINT NN_AMOSTRAS_TALHAO_ID NOT NULL,
    cliente_id NUMBER CONSTRAINT NN_AMOSTRAS_CLIENTE_ID NOT NULL,
    laboratorio_id NUMBER CONSTRAINT NN_AMOSTRAS_LAB_ID NOT NULL,
    importacao_id NUMBER,
    codigo_interno VARCHAR2(50) CONSTRAINT NN_AMOSTRAS_COD_INTERNO NOT NULL,
    codigo_barras VARCHAR2(64),
    tipo_amostra VARCHAR2(20) CONSTRAINT NN_AMOSTRAS_TIPO NOT NULL,
    descricao CLOB,
    lote VARCHAR2(50),
    tonelada NUMBER(12,3),
    metodo_extracao VARCHAR2(50),
    data_coleta DATE,
    data_entrada DATE CONSTRAINT NN_AMOSTRAS_DATA_ENTRADA NOT NULL,
    data_saida DATE,
    status VARCHAR2(20) CONSTRAINT NN_AMOSTRAS_STATUS NOT NULL,
    prioridade VARCHAR2(10) DEFAULT 'MEDIA' CONSTRAINT NN_AMOSTRAS_PRIORIDADE NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_AMOSTRAS_CRIADO_EM NOT NULL,
    CONSTRAINT UQ_AMOSTRAS_COD_INTERNO_LAB UNIQUE (laboratorio_id, codigo_interno),
    CONSTRAINT CK_AMOSTRAS_TIPO CHECK (tipo_amostra IN ('SOLO','FERTILIZANTE','FOLHA','SEMENTE','PRAGA')),
    CONSTRAINT CK_AMOSTRAS_STATUS CHECK (status IN ('RECEBIDA','IMPORTADA','EM_ANALISE','REVISAO','LAUDO_GERADO','ENVIADA','CANCELADA')),
    CONSTRAINT CK_AMOSTRAS_PRIORIDADE CHECK (prioridade IN ('BAIXA','MEDIA','ALTA','URGENTE')),
    CONSTRAINT CK_AMOSTRAS_DATAS CHECK (data_saida IS NULL OR data_saida >= data_entrada),
    CONSTRAINT FK_AMOSTRAS_TALHOES FOREIGN KEY (talhao_id) REFERENCES talhoes(id),
    CONSTRAINT FK_AMOSTRAS_CLIENTES FOREIGN KEY (cliente_id) REFERENCES usuarios(id),
    CONSTRAINT FK_AMOSTRAS_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_AMOSTRAS_IMPORTACOES FOREIGN KEY (importacao_id) REFERENCES importacoes(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE configuracoes_calculo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_CONFIG_CALC PRIMARY KEY,
    laboratorio_id NUMBER,
    tipo_laudo VARCHAR2(20) CONSTRAINT NN_CONFIG_CALC_TIPO NOT NULL,
    descricao VARCHAR2(200) CONSTRAINT NN_CONFIG_CALC_DESCRICAO NOT NULL,
    elemento VARCHAR2(100) CONSTRAINT NN_CONFIG_CALC_ELEMENTO NOT NULL,
    formula_matematica CLOB CONSTRAINT NN_CONFIG_CALC_FORMULA NOT NULL,
    unidade_resultado VARCHAR2(30),
    ativo CHAR(1) DEFAULT 'Y' CONSTRAINT NN_CONFIG_CALC_ATIVO NOT NULL,
    versao NUMBER(6,2) CONSTRAINT NN_CONFIG_CALC_VERSAO NOT NULL,
    ordem_execucao NUMBER CONSTRAINT NN_CONFIG_CALC_ORDEM NOT NULL,
    substituido_por NUMBER,
    valido_de DATE CONSTRAINT NN_CONFIG_CALC_VALIDO_DE NOT NULL,
    valido_ate DATE,
    CONSTRAINT CK_CONFIG_CALC_TIPO CHECK (tipo_laudo IN ('SOLO','FERTILIZANTE','FOLHA','SEMENTE','PRAGA')),
    CONSTRAINT CK_CONFIG_CALC_ATIVO CHECK (ativo IN ('Y','N')),
    CONSTRAINT CK_CONFIG_CALC_VIGENCIA CHECK (valido_ate IS NULL OR valido_ate >= valido_de),
    CONSTRAINT FK_CONFIG_CALC_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_CONFIG_CALC_SUBSTITUIDO_POR FOREIGN KEY (substituido_por) REFERENCES configuracoes_calculo(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE laudos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_LAUDOS PRIMARY KEY,
    amostra_id NUMBER CONSTRAINT NN_LAUDOS_AMOSTRA_ID NOT NULL,
    laboratorio_id NUMBER CONSTRAINT NN_LAUDOS_LAB_ID NOT NULL,
    responsavel_id NUMBER,
    tipo_laudo VARCHAR2(20) CONSTRAINT NN_LAUDOS_TIPO NOT NULL,
    numero_pedido VARCHAR2(50),
    numero_laudo VARCHAR2(50) CONSTRAINT NN_LAUDOS_NUM_LAUDO NOT NULL,
    solicitante_nome VARCHAR2(200),
    razao_social VARCHAR2(200),
    propriedade VARCHAR2(200),
    cidade VARCHAR2(100),
    data_entrada DATE,
    data_saida DATE,
    data_emissao DATE CONSTRAINT NN_LAUDOS_DATA_EMISSAO NOT NULL,
    status VARCHAR2(15) CONSTRAINT NN_LAUDOS_STATUS NOT NULL,
    pdf_path CLOB,
    hash_autenticacao VARCHAR2(128),
    observacoes CLOB,
    responsavel_tecnico_nome VARCHAR2(200),
    responsavel_tecnico_registro VARCHAR2(50),
    credenciamento_mapa VARCHAR2(30),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_LAUDOS_CRIADO_EM NOT NULL,
    CONSTRAINT UQ_LAUDOS_NUM_LAUDO_LAB UNIQUE (laboratorio_id, numero_laudo),
    CONSTRAINT CK_LAUDOS_TIPO CHECK (tipo_laudo IN ('SOLO','FERTILIZANTE','FOLHA','SEMENTE','PRAGA')),
    CONSTRAINT CK_LAUDOS_STATUS CHECK (status IN ('RASCUNHO','EM_REVISAO','APROVADO','EMITIDO','CANCELADO')),
    CONSTRAINT FK_LAUDOS_AMOSTRAS FOREIGN KEY (amostra_id) REFERENCES amostras(id),
    CONSTRAINT FK_LAUDOS_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_LAUDOS_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES usuarios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE laudo_resultados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_LAUDO_RESULTADOS PRIMARY KEY,
    laudo_id NUMBER CONSTRAINT NN_LAUDO_RESULTADOS_LAUDO_ID NOT NULL,
    configuracao_id NUMBER,
    parametro VARCHAR2(120) CONSTRAINT NN_LAUDO_RESULTADOS_PARAMETRO NOT NULL,
    unidade VARCHAR2(30),
    garantia VARCHAR2(50),
    resultado NUMBER(18,6),
    resultado_convertido NUMBER(18,6),
    unidade_convertida VARCHAR2(30),
    classe_interpretativa VARCHAR2(30),
    ordem_exibicao NUMBER CONSTRAINT NN_LAUDO_RESULTADOS_ORDEM NOT NULL,
    fora_spec CHAR(1) DEFAULT 'N' CONSTRAINT NN_LAUDO_RESULTADOS_FORA_SPEC NOT NULL,
    CONSTRAINT CK_LAUDO_RESULTADOS_CLASSE CHECK (classe_interpretativa IS NULL OR classe_interpretativa IN ('MUITO_BAIXO','BAIXO','MEDIO','ADEQUADO','ALTO','MUITO_ALTO','FORA_ESPEC')),
    CONSTRAINT CK_LAUDO_RESULTADOS_FORA_SPEC CHECK (fora_spec IN ('Y','N')),
    CONSTRAINT FK_LAUDO_RESULTADOS_LAUDOS FOREIGN KEY (laudo_id) REFERENCES laudos(id),
    CONSTRAINT FK_LAUDO_RESULTADOS_CONFIG FOREIGN KEY (configuracao_id) REFERENCES configuracoes_calculo(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE arquivos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_ARQUIVOS PRIMARY KEY,
    laboratorio_id NUMBER CONSTRAINT NN_ARQUIVOS_LAB_ID NOT NULL,
    amostra_id NUMBER,
    laudo_id NUMBER,
    importacao_id NUMBER,
    tipo_arquivo VARCHAR2(20) CONSTRAINT NN_ARQUIVOS_TIPO NOT NULL,
    nome_original VARCHAR2(255) CONSTRAINT NN_ARQUIVOS_NOME_ORIGINAL NOT NULL,
    caminho_arquivo CLOB CONSTRAINT NN_ARQUIVOS_CAMINHO NOT NULL,
    extensao VARCHAR2(10) CONSTRAINT NN_ARQUIVOS_EXTENSAO NOT NULL,
    tamanho NUMBER CONSTRAINT NN_ARQUIVOS_TAMANHO NOT NULL,
    hash_md5 VARCHAR2(32),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_ARQUIVOS_CRIADO_EM NOT NULL,
    CONSTRAINT CK_ARQUIVOS_TIPO CHECK (tipo_arquivo IN ('BRUTO','PREVIEW','PDF_FINAL','CONTRATO','ANEXO')),
    CONSTRAINT FK_ARQUIVOS_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT FK_ARQUIVOS_AMOSTRAS FOREIGN KEY (amostra_id) REFERENCES amostras(id),
    CONSTRAINT FK_ARQUIVOS_LAUDOS FOREIGN KEY (laudo_id) REFERENCES laudos(id),
    CONSTRAINT FK_ARQUIVOS_IMPORTACOES FOREIGN KEY (importacao_id) REFERENCES importacoes(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE variaveis_calculo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_VARIAVEIS_CALC PRIMARY KEY,
    configuracao_id NUMBER CONSTRAINT NN_VARIAVEIS_CALC_CONFIG_ID NOT NULL,
    nome_variavel VARCHAR2(60) CONSTRAINT NN_VARIAVEIS_CALC_NOME NOT NULL,
    origem_variavel VARCHAR2(20) CONSTRAINT NN_VARIAVEIS_CALC_ORIGEM NOT NULL,
    parametro_ref VARCHAR2(120),
    constante_valor NUMBER(18,6),
    descricao VARCHAR2(200),
    CONSTRAINT UQ_VARIAVEIS_CALC UNIQUE (configuracao_id, nome_variavel),
    CONSTRAINT CK_VARIAVEIS_CALC_ORIGEM CHECK (origem_variavel IN ('AMOSTRA','RESULTADO','CONSTANTE','LIMITE')),
    CONSTRAINT FK_VARIAVEIS_CALC_CONFIG FOREIGN KEY (configuracao_id) REFERENCES configuracoes_calculo(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /
    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE limites_referencia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_LIMITES_REF PRIMARY KEY,
    configuracao_id NUMBER CONSTRAINT NN_LIMITES_REF_CONFIG_ID NOT NULL,
    cultura VARCHAR2(80),
    classe VARCHAR2(30) CONSTRAINT NN_LIMITES_REF_CLASSE NOT NULL,
    valor_minimo NUMBER(18,6),
    valor_maximo NUMBER(18,6),
    unidade VARCHAR2(30),
    bioma VARCHAR2(20),
    metodo_extracao VARCHAR2(50),
    versao NUMBER(6,2) CONSTRAINT NN_LIMITES_REF_VERSAO NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_LIMITES_REF_CRIADO_EM NOT NULL,
    CONSTRAINT CK_LIMITES_REF_CLASSE CHECK (classe IN ('MUITO_BAIXO','BAIXO','MEDIO','ADEQUADO','ALTO','MUITO_ALTO')),
    CONSTRAINT CK_LIMITES_REF_INTERVALO CHECK (valor_minimo IS NULL OR valor_maximo IS NULL OR valor_maximo >= valor_minimo),
    CONSTRAINT FK_LIMITES_REF_CONFIG FOREIGN KEY (configuracao_id) REFERENCES configuracoes_calculo(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /

COMMENT ON TABLE importacoes IS 'Arquivos brutos importados e seu estado de processamento.';
COMMENT ON COLUMN importacoes.id IS 'Identificador da importação.';
COMMENT ON COLUMN importacoes.laboratorio_id IS 'Laboratório dono da importação.';
COMMENT ON COLUMN importacoes.usuario_id IS 'Usuário que enviou o arquivo.';
COMMENT ON COLUMN importacoes.nome_arquivo IS 'Nome original.';
COMMENT ON COLUMN importacoes.tipo_arquivo IS 'CSV ou XLSX.';
COMMENT ON COLUMN importacoes.formato_instrumento IS 'Origem/formato do equipamento.';
COMMENT ON COLUMN importacoes.caminho_arquivo IS 'Caminho lógico/físico.';
COMMENT ON COLUMN importacoes.hash_arquivo IS 'Hash de integridade.';
COMMENT ON COLUMN importacoes.status IS 'ENVIADO, PROCESSANDO, PROCESSADO, ERRO.';
COMMENT ON COLUMN importacoes.mensagem_erro IS 'Erro de processamento.';
COMMENT ON COLUMN importacoes.total_registros IS 'Total esperado.';
COMMENT ON COLUMN importacoes.registros_processados IS 'Registros processados.';
COMMENT ON COLUMN importacoes.criado_em IS 'Criação.';
COMMENT ON COLUMN importacoes.processado_em IS 'Fim do processamento.';
COMMENT ON TABLE amostras IS 'Registro de amostras enviadas ao laboratório.';
COMMENT ON COLUMN amostras.id IS 'Identificador da amostra.';
COMMENT ON COLUMN amostras.talhao_id IS 'Talhão de origem.';
COMMENT ON COLUMN amostras.cliente_id IS 'Cliente/produtor.';
COMMENT ON COLUMN amostras.laboratorio_id IS 'Laboratório responsável.';
COMMENT ON COLUMN amostras.importacao_id IS 'Importação origem.';
COMMENT ON COLUMN amostras.codigo_interno IS 'Código interno do laboratório.';
COMMENT ON COLUMN amostras.codigo_barras IS 'Código de barras.';
COMMENT ON COLUMN amostras.tipo_amostra IS 'SOLO, FERTILIZANTE, FOLHA, SEMENTE, PRAGA.';
COMMENT ON COLUMN amostras.descricao IS 'Descrição complementar.';
COMMENT ON COLUMN amostras.lote IS 'Lote associado.';
COMMENT ON COLUMN amostras.tonelada IS 'Tonelagem, quando aplicável.';
COMMENT ON COLUMN amostras.metodo_extracao IS 'Método de extração.';
COMMENT ON COLUMN amostras.data_coleta IS 'Data de coleta.';
COMMENT ON COLUMN amostras.data_entrada IS 'Entrada no laboratório.';
COMMENT ON COLUMN amostras.data_saida IS 'Saída/conclusão.';
COMMENT ON COLUMN amostras.status IS 'RECEBIDA, IMPORTADA, EM_ANALISE, REVISAO, LAUDO_GERADO, ENVIADA, CANCELADA.';
COMMENT ON COLUMN amostras.prioridade IS 'BAIXA, MEDIA, ALTA, URGENTE.';
COMMENT ON COLUMN amostras.criado_em IS 'Criação.';
COMMENT ON TABLE configuracoes_calculo IS 'Regras e fórmulas parametrizadas do motor de cálculo.';
COMMENT ON COLUMN configuracoes_calculo.id IS 'Identificador da configuração.';
COMMENT ON COLUMN configuracoes_calculo.laboratorio_id IS 'Laboratório dono; nulo para regra global.';
COMMENT ON COLUMN configuracoes_calculo.tipo_laudo IS 'Tipo de laudo.';
COMMENT ON COLUMN configuracoes_calculo.descricao IS 'Descrição da regra.';
COMMENT ON COLUMN configuracoes_calculo.elemento IS 'Elemento/indicador calculado.';
COMMENT ON COLUMN configuracoes_calculo.formula_matematica IS 'Expressão da fórmula.';
COMMENT ON COLUMN configuracoes_calculo.unidade_resultado IS 'Unidade do resultado.';
COMMENT ON COLUMN configuracoes_calculo.ativo IS 'Indicador Y/N.';
COMMENT ON COLUMN configuracoes_calculo.versao IS 'Versão da regra.';
COMMENT ON COLUMN configuracoes_calculo.ordem_execucao IS 'Ordem de execução.';
COMMENT ON COLUMN configuracoes_calculo.substituido_por IS 'Nova configuração que substitui a atual.';
COMMENT ON COLUMN configuracoes_calculo.valido_de IS 'Início da validade.';
COMMENT ON COLUMN configuracoes_calculo.valido_ate IS 'Fim da validade.';
COMMENT ON TABLE laudos IS 'Cabeçalho e metadados de laudos emitidos.';
COMMENT ON COLUMN laudos.id IS 'Identificador do laudo.';
COMMENT ON COLUMN laudos.amostra_id IS 'Amostra analisada.';
COMMENT ON COLUMN laudos.laboratorio_id IS 'Laboratório emissor.';
COMMENT ON COLUMN laudos.responsavel_id IS 'Usuário responsável interno.';
COMMENT ON COLUMN laudos.tipo_laudo IS 'SOLO, FERTILIZANTE, FOLHA, SEMENTE, PRAGA.';
COMMENT ON COLUMN laudos.numero_pedido IS 'Número do pedido.';
COMMENT ON COLUMN laudos.numero_laudo IS 'Número do laudo.';
COMMENT ON COLUMN laudos.solicitante_nome IS 'Solicitante exibido no PDF.';
COMMENT ON COLUMN laudos.razao_social IS 'Razão social exibida.';
COMMENT ON COLUMN laudos.propriedade IS 'Nome da propriedade.';
COMMENT ON COLUMN laudos.cidade IS 'Cidade exibida.';
COMMENT ON COLUMN laudos.data_entrada IS 'Entrada informada no laudo.';
COMMENT ON COLUMN laudos.data_saida IS 'Saída informada no laudo.';
COMMENT ON COLUMN laudos.data_emissao IS 'Emissão.';
COMMENT ON COLUMN laudos.status IS 'RASCUNHO, EM_REVISAO, APROVADO, EMITIDO, CANCELADO.';
COMMENT ON COLUMN laudos.pdf_path IS 'Caminho do PDF.';
COMMENT ON COLUMN laudos.hash_autenticacao IS 'Hash/código de autenticação.';
COMMENT ON COLUMN laudos.observacoes IS 'Observações técnicas.';
COMMENT ON COLUMN laudos.responsavel_tecnico_nome IS 'Responsável técnico impresso.';
COMMENT ON COLUMN laudos.responsavel_tecnico_registro IS 'Registro profissional impresso.';
COMMENT ON COLUMN laudos.credenciamento_mapa IS 'Credenciamento MAPA.';
COMMENT ON COLUMN laudos.criado_em IS 'Criação.';
COMMENT ON TABLE laudo_resultados IS 'Linhas de resultados analíticos exibidos em cada laudo.';
COMMENT ON COLUMN laudo_resultados.id IS 'Identificador do resultado.';
COMMENT ON COLUMN laudo_resultados.laudo_id IS 'Laudo pai.';
COMMENT ON COLUMN laudo_resultados.configuracao_id IS 'Configuração de cálculo associada.';
COMMENT ON COLUMN laudo_resultados.parametro IS 'Nome do parâmetro.';
COMMENT ON COLUMN laudo_resultados.unidade IS 'Unidade original.';
COMMENT ON COLUMN laudo_resultados.garantia IS 'Faixa/garantia contratual.';
COMMENT ON COLUMN laudo_resultados.resultado IS 'Resultado original.';
COMMENT ON COLUMN laudo_resultados.resultado_convertido IS 'Resultado convertido.';
COMMENT ON COLUMN laudo_resultados.unidade_convertida IS 'Unidade convertida.';
COMMENT ON COLUMN laudo_resultados.classe_interpretativa IS 'Classe interpretativa.';
COMMENT ON COLUMN laudo_resultados.ordem_exibicao IS 'Ordem no PDF.';
COMMENT ON COLUMN laudo_resultados.fora_spec IS 'Indicador Y/N.';
COMMENT ON TABLE arquivos IS 'Repositório lógico de arquivos brutos e gerados.';
COMMENT ON COLUMN arquivos.id IS 'Identificador do arquivo.';
COMMENT ON COLUMN arquivos.laboratorio_id IS 'Laboratório dono.';
COMMENT ON COLUMN arquivos.amostra_id IS 'Amostra relacionada.';
COMMENT ON COLUMN arquivos.laudo_id IS 'Laudo relacionado.';
COMMENT ON COLUMN arquivos.importacao_id IS 'Importação relacionada.';
COMMENT ON COLUMN arquivos.tipo_arquivo IS 'BRUTO, PREVIEW, PDF_FINAL, CONTRATO, ANEXO.';
COMMENT ON COLUMN arquivos.nome_original IS 'Nome original.';
COMMENT ON COLUMN arquivos.caminho_arquivo IS 'Caminho lógico/físico.';
COMMENT ON COLUMN arquivos.extensao IS 'Extensão.';
COMMENT ON COLUMN arquivos.tamanho IS 'Tamanho em bytes.';
COMMENT ON COLUMN arquivos.hash_md5 IS 'Hash MD5.';
COMMENT ON COLUMN arquivos.criado_em IS 'Criação.';
COMMENT ON TABLE variaveis_calculo IS 'Variáveis utilizadas nas fórmulas parametrizadas.';
COMMENT ON COLUMN variaveis_calculo.id IS 'Identificador da variável.';
COMMENT ON COLUMN variaveis_calculo.configuracao_id IS 'Configuração pai.';
COMMENT ON COLUMN variaveis_calculo.nome_variavel IS 'Símbolo da variável.';
COMMENT ON COLUMN variaveis_calculo.origem_variavel IS 'AMOSTRA, RESULTADO, CONSTANTE, LIMITE.';
COMMENT ON COLUMN variaveis_calculo.parametro_ref IS 'Parâmetro de referência.';
COMMENT ON COLUMN variaveis_calculo.constante_valor IS 'Valor constante.';
COMMENT ON COLUMN variaveis_calculo.descricao IS 'Descrição.';
COMMENT ON TABLE limites_referencia IS 'Faixas de referência e classes interpretativas por configuração.';
COMMENT ON COLUMN limites_referencia.id IS 'Identificador do limite.';
COMMENT ON COLUMN limites_referencia.configuracao_id IS 'Configuração associada.';
COMMENT ON COLUMN limites_referencia.cultura IS 'Cultura agrícola.';
COMMENT ON COLUMN limites_referencia.classe IS 'Classe interpretativa.';
COMMENT ON COLUMN limites_referencia.valor_minimo IS 'Valor mínimo.';
COMMENT ON COLUMN limites_referencia.valor_maximo IS 'Valor máximo.';
COMMENT ON COLUMN limites_referencia.unidade IS 'Unidade do limite.';
COMMENT ON COLUMN limites_referencia.bioma IS 'Bioma aplicável.';
COMMENT ON COLUMN limites_referencia.metodo_extracao IS 'Método aplicável.';
COMMENT ON COLUMN limites_referencia.versao IS 'Versão.';
COMMENT ON COLUMN limites_referencia.criado_em IS 'Criação.';
