-- AgroGemini Oracle v4 - separação por grupos lógicos
-- Arquivo: 05_auditoria.sql
-- Objetivo: tabela de auditoria e trigger de rastreabilidade em laudos.

    BEGIN
        EXECUTE IMMEDIATE q'~
CREATE TABLE eventos_auditoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_EVENTOS_AUD PRIMARY KEY,
    usuario_id NUMBER,
    laboratorio_id NUMBER,
    tabela_afetada VARCHAR2(60) CONSTRAINT NN_EVENTOS_AUD_TABELA NOT NULL,
    registro_id NUMBER CONSTRAINT NN_EVENTOS_AUD_REGISTRO_ID NOT NULL,
    operacao VARCHAR2(10) CONSTRAINT NN_EVENTOS_AUD_OPERACAO NOT NULL,
    dados_anteriores CLOB,
    dados_novos CLOB,
    ip_origem VARCHAR2(45),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN_EVENTOS_AUD_CRIADO_EM NOT NULL,
    CONSTRAINT CK_EVENTOS_AUD_OPERACAO CHECK (operacao IN ('INSERT','UPDATE','DELETE','LOGIN','DOWNLOAD')),
    CONSTRAINT FK_EVENTOS_AUD_USUARIOS FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT FK_EVENTOS_AUD_LABS FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id)
)
~';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    /


COMMENT ON TABLE eventos_auditoria IS 'Trilha de auditoria de ações relevantes na plataforma.';
COMMENT ON COLUMN eventos_auditoria.id IS 'Identificador do evento.';
COMMENT ON COLUMN eventos_auditoria.usuario_id IS 'Usuário que executou a ação.';
COMMENT ON COLUMN eventos_auditoria.laboratorio_id IS 'Tenant afetado.';
COMMENT ON COLUMN eventos_auditoria.tabela_afetada IS 'Tabela alterada.';
COMMENT ON COLUMN eventos_auditoria.registro_id IS 'Registro afetado.';
COMMENT ON COLUMN eventos_auditoria.operacao IS 'INSERT, UPDATE, DELETE, LOGIN, DOWNLOAD.';
COMMENT ON COLUMN eventos_auditoria.dados_anteriores IS 'Payload anterior.';
COMMENT ON COLUMN eventos_auditoria.dados_novos IS 'Payload novo.';
COMMENT ON COLUMN eventos_auditoria.ip_origem IS 'IP de origem.';
COMMENT ON COLUMN eventos_auditoria.criado_em IS 'Data do evento.';

CREATE OR REPLACE TRIGGER TR_AUD_LAUDOS
AFTER INSERT OR UPDATE OR DELETE ON laudos
FOR EACH ROW
DECLARE
    v_usuario_id     NUMBER;
    v_laboratorio_id NUMBER;
    v_ip_origem      VARCHAR2(100);
    v_operacao       VARCHAR2(10);
BEGIN
    BEGIN
        v_usuario_id := TO_NUMBER(NULLIF(SYS_CONTEXT('AGRO_CTX','USUARIO_ID'), ''));
    EXCEPTION
        WHEN OTHERS THEN
            v_usuario_id := NULL;
    END;

    BEGIN
        v_laboratorio_id := TO_NUMBER(NULLIF(SYS_CONTEXT('AGRO_CTX','LABORATORIO_ID'), ''));
    EXCEPTION
        WHEN OTHERS THEN
            v_laboratorio_id := NULL;
    END;

    BEGIN
        v_ip_origem := SYS_CONTEXT('AGRO_CTX','IP_ORIGEM');
    EXCEPTION
        WHEN OTHERS THEN
            v_ip_origem := NULL;
    END;

    IF INSERTING THEN
        v_operacao := 'INSERT';
        INSERT INTO eventos_auditoria (
            id, usuario_id, laboratorio_id, tabela_afetada, registro_id, operacao,
            dados_anteriores, dados_novos, ip_origem, criado_em
        ) VALUES (
            DEFAULT, v_usuario_id, NVL(v_laboratorio_id, :NEW.laboratorio_id), 'LAUDOS', :NEW.id, v_operacao,
            NULL,
            TO_CLOB(JSON_OBJECT(
                'id' VALUE :NEW.id,
                'amostra_id' VALUE :NEW.amostra_id,
                'status' VALUE :NEW.status,
                'numero_laudo' VALUE :NEW.numero_laudo
            )),
            v_ip_origem,
            SYSTIMESTAMP
        );
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        INSERT INTO eventos_auditoria (
            id, usuario_id, laboratorio_id, tabela_afetada, registro_id, operacao,
            dados_anteriores, dados_novos, ip_origem, criado_em
        ) VALUES (
            DEFAULT, v_usuario_id, NVL(v_laboratorio_id, :NEW.laboratorio_id), 'LAUDOS', :NEW.id, v_operacao,
            TO_CLOB(JSON_OBJECT(
                'id' VALUE :OLD.id,
                'status' VALUE :OLD.status,
                'numero_laudo' VALUE :OLD.numero_laudo
            )),
            TO_CLOB(JSON_OBJECT(
                'id' VALUE :NEW.id,
                'status' VALUE :NEW.status,
                'numero_laudo' VALUE :NEW.numero_laudo
            )),
            v_ip_origem,
            SYSTIMESTAMP
        );
    ELSIF DELETING THEN
        v_operacao := 'DELETE';
        INSERT INTO eventos_auditoria (
            id, usuario_id, laboratorio_id, tabela_afetada, registro_id, operacao,
            dados_anteriores, dados_novos, ip_origem, criado_em
        ) VALUES (
            DEFAULT, v_usuario_id, NVL(v_laboratorio_id, :OLD.laboratorio_id), 'LAUDOS', :OLD.id, v_operacao,
            TO_CLOB(JSON_OBJECT(
                'id' VALUE :OLD.id,
                'status' VALUE :OLD.status,
                'numero_laudo' VALUE :OLD.numero_laudo
            )),
            NULL,
            v_ip_origem,
            SYSTIMESTAMP
        );
    END IF;
END;
/
