-- AgroGemini Oracle v4 - separação por grupos lógicos
-- Arquivo: 07_sequences.sql
-- Objetivo: sequences explícitas.
-- Observação: no schema consolidado atual, as PKs usam
-- "GENERATED BY DEFAULT AS IDENTITY" e não há CREATE SEQUENCE explícito.

-- Sem objetos neste arquivo no momento.
