-- 17. FATURAMENTO E NOVOS PLANOS
-- Adiciona tabela de metricas financeiras e atualiza as restricoes de planos

-- 1. Criação da tabela de faturamento historico
BEGIN
    EXECUTE IMMEDIATE q'~
CREATE TABLE faturamento_historico (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_FATURAMENTO PRIMARY KEY,
    ano_mes VARCHAR2(7) CONSTRAINT NN_FATURAMENTO_ANO_MES NOT NULL, -- Ex: 2026-05
    receita_mensal NUMBER(12,2) DEFAULT 0 NOT NULL,
    receita_esperada NUMBER(12,2) DEFAULT 0 NOT NULL,
    crescimento_percentual NUMBER(5,2) DEFAULT 0,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_FATURAMENTO_ANO_MES UNIQUE (ano_mes)
)
~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 2. Atualizar as Constraints de Planos na Tabela PLANOS_ASSINATURAS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE planos_assinaturas DROP CONSTRAINT CK_PLANOS_TIPO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            NULL;
        END IF;
END;
/

-- Opcional: recriar a constraint com os novos tipos ou deixar sem constraint para flexibilidade
-- Como o usuário pediu tipos específicos, vamos apenas remover a antiga para não travar inserções.

-- 3. Inserir os novos planos base se não existirem
BEGIN
    INSERT INTO planos_assinaturas (id, tipo, valor, descricao, limite_amostras, limite_usuarios, permite_api, ativo)
    SELECT 3, 'FREE', 0.00, 'Plano gratuito para lab e produtor', 10, 1, 'N', 'Y' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM planos_assinaturas WHERE tipo = 'FREE');

    INSERT INTO planos_assinaturas (id, tipo, valor, descricao, limite_amostras, limite_usuarios, permite_api, ativo)
    SELECT 4, 'PREMIUM LAB', 1299.90, 'Plano premium para laboratório', 5000, 50, 'Y', 'Y' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM planos_assinaturas WHERE tipo = 'PREMIUM LAB');

    INSERT INTO planos_assinaturas (id, tipo, valor, descricao, limite_amostras, limite_usuarios, permite_api, ativo)
    SELECT 5, 'PREMIUM PROD', 199.90, 'Plano premium para produtor', 500, 5, 'N', 'Y' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM planos_assinaturas WHERE tipo = 'PREMIUM PROD');

    INSERT INTO planos_assinaturas (id, tipo, valor, descricao, limite_amostras, limite_usuarios, permite_api, ativo)
    SELECT 6, 'FUNCIONARIO LAB', 0.00, 'Acesso restrito a funcionarios do lab', 0, 1, 'N', 'Y' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM planos_assinaturas WHERE tipo = 'FUNCIONARIO LAB');

    INSERT INTO planos_assinaturas (id, tipo, valor, descricao, limite_amostras, limite_usuarios, permite_api, ativo)
    SELECT 7, 'ADM-PLAN', 0.00, 'Plano administrativo do sistema', 999999, 999, 'Y', 'Y' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM planos_assinaturas WHERE tipo = 'ADM-PLAN');

    INSERT INTO planos_assinaturas (id, tipo, valor, descricao, limite_amostras, limite_usuarios, permite_api, ativo)
    SELECT 8, 'FILIAL LAB', 499.90, 'Acesso para filiais de lab', 500, 10, 'Y', 'Y' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM planos_assinaturas WHERE tipo = 'FILIAL LAB');
    
    COMMIT;
END;
/

-- 4. Atualizar as Constraints de plano_ativo na Tabela USUARIOS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE usuarios DROP CONSTRAINT CK_USUARIOS_PLANO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            NULL;
        END IF;
END;
/

-- Atualizar os usuarios existentes para os novos planos
BEGIN
    UPDATE usuarios SET plano_ativo = 'ADM-PLAN' WHERE tipo_usuario = 'ADM';
    UPDATE usuarios SET plano_ativo = 'PREMIUM LAB' WHERE tipo_usuario = 'UP';
    UPDATE usuarios SET plano_ativo = 'FUNCIONARIO LAB' WHERE tipo_usuario = 'UC';
    UPDATE usuarios SET plano_ativo = 'PREMIUM PROD' WHERE tipo_usuario = 'UE' AND plano_ativo = 'PREMIUM';
    UPDATE usuarios SET plano_ativo = 'FREE' WHERE plano_ativo IS NULL OR plano_ativo = 'BASICO';
    COMMIT;
END;
