[pytest]
asyncio_mode = auto
testpaths = app/tests
addopts =
    -v
    --tb=short
    --cov=app
    --cov-report=term-missing
    --cov-report=html:app/tests/htmlcov
    --cov-report=xml:app/tests/coverage.xml
    --cov-config=.coveragerc
    -p no:warnings
