import asyncio
from app.db.database import AsyncSessionLocal
from app.models.base import Base
from sqlalchemy import text
import app.models.comercial
import app.models.laboratorio
import app.models.usuario

async def test():
    async with AsyncSessionLocal() as session:
        for table_name, table in Base.metadata.tables.items():
            if 'id' in table.columns:
                col = table.columns['id']
                if hasattr(col, 'identity') and col.identity is not None:
                    print(f"Resyncing identity for {table_name}...")
                    try:
                        await session.execute(text(f"ALTER TABLE {table_name} MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)"))
                    except Exception as e:
                        print(f"Failed on {table_name}: {e}")
        await session.commit()
        print("Done")

if __name__ == "__main__":
    asyncio.run(test())
