import asyncio
from app.db.database import AsyncSessionLocal
from sqlalchemy import text

async def test():
    async with AsyncSessionLocal() as session:
        try:
            await session.execute(text("ALTER TABLE planos_assinaturas MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)"))
            await session.commit()
            print("SUCCESS")
        except Exception as e:
            print(f"FAILED: {e}")

if __name__ == "__main__":
    asyncio.run(test())
