"""Unified Baseline v5 with Admin and Permissions

Revision ID: 166cdf55addb
Revises: 
Create Date: 2026-05-09 15:58:22.918484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166cdf55addb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_metricas_consolidadas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('assinantes_ativos', sa.Integer(), nullable=False),
    sa.Column('novas_assinaturas_mes', sa.Integer(), nullable=False),
    sa.Column('cancelamentos_mes', sa.Integer(), nullable=False),
    sa.Column('renovacoes_mes', sa.Integer(), nullable=False),
    sa.Column('retornantes_mes', sa.Integer(), nullable=False),
    sa.Column('mrr_estimado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amostras_mes', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_referencia')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('pais', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissoes_sistema',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('planos_assinaturas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('limite_amostras', sa.Integer(), nullable=False),
    sa.Column('limite_usuarios', sa.Integer(), nullable=False),
    sa.Column('permite_api', sa.CHAR(length=1), nullable=False),
    sa.Column('ativo', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint("ativo IN ('Y','N')"),
    sa.CheckConstraint("permite_api IN ('Y','N')"),
    sa.CheckConstraint("tipo IN ('BASICO','PREMIUM')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('fazendas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('area_total_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("REGEXP_LIKE(cpf_cnpj, '^[0-9]{11,14}$')"),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratorios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('ativo', sa.CHAR(length=1), nullable=False),
    sa.Column('acreditacao_iso17025', sa.CHAR(length=1), nullable=False),
    sa.Column('registro_renasem', sa.String(length=30), nullable=True),
    sa.Column('credenciamento_mapa', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("REGEXP_LIKE(cnpj, '^[0-9]{14}$')"),
    sa.CheckConstraint("acreditacao_iso17025 IN ('Y','N')"),
    sa.CheckConstraint("ativo IN ('Y','N')"),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=3), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.CHAR(length=1), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plano_ativo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=False),
    sa.Column('arquivo_contrato', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('renovacao_automatica', sa.CHAR(length=1), nullable=False),
    sa.Column('amostras_consumidas', sa.Integer(), nullable=False),
    sa.CheckConstraint("renovacao_automatica IN ('Y','N')"),
    sa.CheckConstraint("status IN ('ATIVA','SUSPENSA','CANCELADA','EXPIRADA')"),
    sa.CheckConstraint('data_expiracao >= data_inicio'),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_assinaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato')
    )
    op.create_table('configuracoes_calculo',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=True),
    sa.Column('tipo_laudo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('elemento', sa.String(length=100), nullable=False),
    sa.Column('formula_matematica', sa.Text(), nullable=False),
    sa.Column('unidade_resultado', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.CHAR(length=1), nullable=False),
    sa.Column('versao', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ordem_execucao', sa.Integer(), nullable=False),
    sa.Column('substituido_por', sa.Integer(), nullable=True),
    sa.Column('valido_de', sa.DateTime(), nullable=False),
    sa.Column('valido_ate', sa.DateTime(), nullable=True),
    sa.Column('tipo_execucao', sa.String(length=30), nullable=True),
    sa.Column('modelo_nome', sa.String(length=120), nullable=True),
    sa.Column('modelo_versao', sa.String(length=60), nullable=True),
    sa.Column('feature_store_ref', sa.String(length=240), nullable=True),
    sa.Column('score_confianca_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('parametros_modelo', sa.Text(), nullable=True),
    sa.CheckConstraint("ativo IN ('Y','N')"),
    sa.CheckConstraint("tipo_execucao IS NULL OR tipo_execucao IN ('FORMULA','MODELO_ML','PIPELINE_HIBRIDO')"),
    sa.CheckConstraint("tipo_laudo IN ('SOLO','FERTILIZANTE','FOLHA','SEMENTE','PRAGA')"),
    sa.CheckConstraint('valido_ate IS NULL OR valido_ate >= valido_de'),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['substituido_por'], ['configuracoes_calculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracoes_calculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_calculo_modelo_nome'), ['modelo_nome'], unique=False)

    op.create_table('eventos_auditoria',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('laboratorio_id', sa.Integer(), nullable=True),
    sa.Column('tabela_afetada', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('operacao', sa.String(length=10), nullable=False),
    sa.Column('dados_anteriores', sa.Text(), nullable=True),
    sa.Column('dados_novos', sa.Text(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operacao IN ('INSERT','UPDATE','DELETE','LOGIN','DOWNLOAD')"),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fazenda_usuarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('fazenda_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('inicio_vigencia', sa.DateTime(), nullable=False),
    sa.Column('fim_vigencia', sa.DateTime(), nullable=True),
    sa.CheckConstraint("papel IN ('DONO','FUNCIONARIO','GERENTE')"),
    sa.CheckConstraint('fim_vigencia IS NULL OR fim_vigencia >= inicio_vigencia'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=10), nullable=False),
    sa.Column('formato_instrumento', sa.String(length=40), nullable=True),
    sa.Column('caminho_arquivo', sa.Text(), nullable=False),
    sa.Column('hash_arquivo', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=False),
    sa.Column('registros_processados', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ENVIADO','PROCESSANDO','PROCESSADO','ERRO')"),
    sa.CheckConstraint("tipo_arquivo IN ('CSV','XLSX')"),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratorio_usuarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=25), nullable=False),
    sa.Column('registro_crea', sa.String(length=30), nullable=True),
    sa.CheckConstraint("papel IN ('TECNICO','GESTOR','RESPONSAVEL_TECNICO','ADMINISTRADOR','CLIENTE')", name='CK_LAB_USUARIOS_PAPEL'),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laboratorio_id', 'usuario_id', 'papel')
    )
    op.create_table('talhoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('fazenda_id', sa.Integer(), nullable=False),
    sa.Column('identificacao', sa.String(length=100), nullable=False),
    sa.Column('tipo_plantio', sa.String(length=30), nullable=False),
    sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('profundidade_amostragem_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('textura_solo', sa.String(length=20), nullable=True),
    sa.Column('bioma', sa.String(length=20), nullable=True),
    sa.Column('latitude_centroide', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude_centroide', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("bioma IS NULL OR bioma IN ('AMAZONIA','CERRADO','CAATINGA','MATA_ATLANTICA','PAMPA','PANTANAL')"),
    sa.CheckConstraint("textura_solo IS NULL OR textura_solo IN ('ARENOSA','MEDIA','ARGILOSA','MUITO_ARGILOSA')"),
    sa.CheckConstraint("tipo_plantio IN ('CONVENCIONAL','DIRETO','IRRIGADO','SEQUEIRO','OUTRO')"),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fazenda_id', 'identificacao', name='UQ_TALHOES_FAZENDA_IDENT')
    )
    op.create_table('telefones_laboratorios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.CheckConstraint("tipo IN ('MOVEL','FIXO','COMERCIAL')"),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones_usuarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('whatsapp', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_permissoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permissao_codigo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('CONCEDIDA', 'NEGADA')"),
    sa.ForeignKeyConstraint(['permissao_codigo'], ['permissoes_sistema.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amostras',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('talhao_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('codigo_barras', sa.String(length=64), nullable=True),
    sa.Column('tipo_amostra', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('tonelada', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('metodo_extracao', sa.String(length=50), nullable=True),
    sa.Column('data_coleta', sa.DateTime(), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prioridade', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("prioridade IN ('BAIXA','MEDIA','ALTA','URGENTE')"),
    sa.CheckConstraint("status IN ('RECEBIDA','IMPORTADA','EM_ANALISE','REVISAO','LAUDO_GERADO','ENVIADA','CANCELADA')"),
    sa.CheckConstraint("tipo_amostra IN ('SOLO','FERTILIZANTE','FOLHA','SEMENTE','PRAGA')"),
    sa.CheckConstraint('data_saida IS NULL OR data_saida >= data_entrada'),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laboratorio_id', 'codigo_interno', name='UQ_AMOSTRAS_COD_INTERNO_LAB')
    )
    op.create_table('limites_referencia',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=False),
    sa.Column('cultura', sa.String(length=80), nullable=True),
    sa.Column('classe', sa.String(length=30), nullable=False),
    sa.Column('valor_minimo', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_maximo', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('bioma', sa.String(length=20), nullable=True),
    sa.Column('metodo_extracao', sa.String(length=50), nullable=True),
    sa.Column('versao', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("classe IN ('MUITO_BAIXO','BAIXO','MEDIO','ADEQUADO','ALTO','MUITO_ALTO')"),
    sa.CheckConstraint('valor_minimo IS NULL OR valor_maximo IS NULL OR valor_maximo >= valor_minimo'),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes_calculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variaveis_calculo',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=False),
    sa.Column('nome_variavel', sa.String(length=60), nullable=False),
    sa.Column('origem_variavel', sa.String(length=20), nullable=False),
    sa.Column('parametro_ref', sa.String(length=120), nullable=True),
    sa.Column('constante_valor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.CheckConstraint("origem_variavel IN ('AMOSTRA','RESULTADO','CONSTANTE','LIMITE')"),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes_calculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuracao_id', 'nome_variavel')
    )
    op.create_table('laudos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('amostra_id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('tipo_laudo', sa.String(length=20), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=True),
    sa.Column('numero_laudo', sa.String(length=50), nullable=False),
    sa.Column('solicitante_nome', sa.String(length=200), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('propriedade', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('hash_autenticacao', sa.String(length=128), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('responsavel_tecnico_nome', sa.String(length=200), nullable=True),
    sa.Column('responsavel_tecnico_registro', sa.String(length=50), nullable=True),
    sa.Column('credenciamento_mapa', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('RASCUNHO','EM_REVISAO','APROVADO','EMITIDO','CANCELADO')"),
    sa.CheckConstraint("tipo_laudo IN ('SOLO','FERTILIZANTE','FOLHA','SEMENTE','PRAGA')"),
    sa.ForeignKeyConstraint(['amostra_id'], ['amostras.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laboratorio_id', 'numero_laudo', name='UQ_LAUDOS_NUM_LAUDO_LAB')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('amostra_id', sa.Integer(), nullable=True),
    sa.Column('laudo_id', sa.Integer(), nullable=True),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo_arquivo', sa.String(length=20), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.Text(), nullable=False),
    sa.Column('extensao', sa.String(length=10), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('hash_md5', sa.String(length=32), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo_arquivo IN ('BRUTO','PREVIEW','PDF_FINAL','CONTRATO','ANEXO')"),
    sa.ForeignKeyConstraint(['amostra_id'], ['amostras.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laudo_resultados',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('laudo_id', sa.Integer(), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=True),
    sa.Column('parametro', sa.String(length=120), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('garantia', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('resultado_convertido', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unidade_convertida', sa.String(length=30), nullable=True),
    sa.Column('classe_interpretativa', sa.String(length=30), nullable=True),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=False),
    sa.Column('fora_spec', sa.String(length=1), nullable=False),
    sa.CheckConstraint("classe_interpretativa IS NULL OR classe_interpretativa IN ('MUITO_BAIXO','BAIXO','MEDIO','ADEQUADO','ALTO','MUITO_ALTO','FORA_ESPEC')"),
    sa.CheckConstraint("fora_spec IN ('Y','N')"),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes_calculo.id'], ),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laudo_resultados')
    op.drop_table('arquivos')
    op.drop_table('laudos')
    op.drop_table('variaveis_calculo')
    op.drop_table('limites_referencia')
    op.drop_table('amostras')
    op.drop_table('usuario_permissoes')
    op.drop_table('telefones_usuarios')
    op.drop_table('telefones_laboratorios')
    op.drop_table('talhoes')
    op.drop_table('laboratorio_usuarios')
    op.drop_table('importacoes')
    op.drop_table('fazenda_usuarios')
    op.drop_table('eventos_auditoria')
    with op.batch_alter_table('configuracoes_calculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_calculo_modelo_nome'))

    op.drop_table('configuracoes_calculo')
    op.drop_table('assinaturas')
    op.drop_table('usuarios')
    op.drop_table('laboratorios')
    op.drop_table('fazendas')
    op.drop_table('planos_assinaturas')
    op.drop_table('permissoes_sistema')
    op.drop_table('enderecos')
    op.drop_table('admin_metricas_consolidadas')
    # ### end Alembic commands ###
