"""Add Faturamento Historico e novos Planos

Revision ID: 9b48232b407e
Revises: 7adb139a54b5
Create Date: 2026-05-26 18:34:13.108500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b48232b407e'
down_revision: Union[str, Sequence[str], None] = '7adb139a54b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturamento_historico',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('ano_mes', sa.String(length=7), nullable=False),
    sa.Column('receita_mensal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receita_esperada', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('crescimento_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_mes')
    )
    pass

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('plano_ativo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('plano_ativo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    pass

    op.drop_table('faturamento_historico')
    # ### end Alembic commands ###
